### ISSUE TITLE
ui bug in autocomplete dropdown

### ISSUE THREAD

**Issue by marcoamt** [hoaphantn7604/react-native-element-textinput#1]
Hi man, when I have more than x items in data array, when I try to scroll this bug appears on dropdown(the example is in a blank app):

![IMG_E84DA6B95739-1](https://user-images.githubusercontent.com/48435302/155573150-e6ab0609-ecd3-402c-b19e-617fb9cd2352.jpeg)

**Comment by hoaphantn7604** [comment]
Hi @marcoamt ,
I’m working on it.

**Comment by marcoamt** [comment]
> Hi @marcoamt ,
> 
> I’m working on it.

Thank's,I hope next week it's fixed. 🙂

**Comment by hoaphantn7604** [comment]
hi @marcoamt ,
This issue is resolve. Please install later version.
